name: Repository Dispatch
on:
  repository_dispatch:
    types: [build]

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - name: Log Client Payload Env Variable
        run: echo ${{ github.event.client_payload.env }}
      - name: Log Github event name
        run: echo $GITHUB_EVENT_NAME
